services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - postgres
    restart: on-failure
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
